import { Transaction } from 'braintree';

// Modeled on a real Braintree sandbox `sale` response (CreditCard, submitted_for_settlement),
// trimmed to the fields the codebase actually reads plus enough of the rest to stay realistic.
export const mockBraintreeTransaction: Transaction = {
  id: 'txn-test-1',
  status: 'submitted_for_settlement',
  type: 'sale',
  currencyIsoCode: 'GBP',
  amount: '1200.00',
  merchantAccountId: 'test-merchant-account',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  customer: { id: 'bt-customer-1' },
  billing: {
    postalCode: '10115',
    countryCodeAlpha2: 'DE',
  },
  refundIds: [],
  paymentInstrumentType: 'credit_card',
  avsErrorResponseCode: '',
  avsPostalCodeResponseCode: 'M',
  avsStreetAddressResponseCode: 'I',
  cvvResponseCode: 'M',
  additionalProcessorResponse: '',
  processorAuthorizationCode: 'AUTH123',
  processorResponseCode: '1000',
  processorResponseText: 'Approved',
  processorResponseType: 'approved',
  processorSettlementResponseCode: '',
  processorSettlementResponseText: '',
  creditCard: {
    bin: '401288',
    cardType: 'Visa',
    commercial: 'Unknown',
    countryOfIssuance: 'Unknown',
    customerLocation: 'US',
    debit: 'Unknown',
    durbinRegulated: 'Unknown',
    expirationMonth: '12',
    expirationYear: '2027',
    healthcare: 'Unknown',
    issuingBank: 'Unknown',
    last4: '1881',
    maskedNumber: '401288******1881',
    payroll: 'Unknown',
    prepaid: 'No',
    productId: 'Unknown',
    token: 'cc-test-token',
    uniqueNumberIdentifier: 'test-unique-number-identifier',
  },
  statusHistory: [
    {
      timestamp: '2024-01-01T00:00:00.000Z',
      status: 'authorized',
      amount: '1200.00',
      user: 'test@example.com',
      transactionSource: 'api',
    },
    {
      timestamp: '2024-01-01T00:00:00.000Z',
      status: 'submitted_for_settlement',
      amount: '1200.00',
      user: 'test@example.com',
      transactionSource: 'api',
    },
  ],
  channel: 'commercetoolsGmbH_SP_BT',
  discountAmount: '0.00',
  networkTransactionId: 'test-network-transaction-id',
  authorizationExpiresAt: '2024-01-08T00:00:00.000Z',
  taxExempt: false,
  recurring: false,
};
