version: "3.8"

services:
  jwt-server:
    image: node:alpine
    restart: always
    command: 
      - npx
      - --package
      - jwt-mock-server
      - -y
      - start
    environment:
      - PORT=9002
    ports:
      - 9002:9002
